### ISSUE TITLE
split.by in plot_cpdb

### ISSUE THREAD

**Issue by saeedfc** [zktuong/ktplots#1]
Hi,

Thanks for this cool package. I was wondering, why the function insists on a  binary factor to split.by argument in plot_cpdb? I saw your original code, where if the 'split.by' column has levels larger than 2, the function will return error asking to use a binary column.

For instance, I have 3 diseases in my experiment and wanted to see them differentially. 
`Error in plot_cpdb("Mes_I", "Treg_I", scdata = SOO, idents = "Type", : please pick another column that is binary`
Would be really cool if this part can be improved?

Thanks again!

**Comment by zktuong** [comment]
Hi, 

thanks for using this.

I've updated the code for plot_cpdb slightly. Can you try now and see if it now handles more than 2 levels?

Cheers
K

**Comment by saeedfc** [comment]
Hi,

thanks. Was my first pull request and I wasn't careful enough. Small change is required to the grep on colnames of means and pvals. Now the function do not recognise the colnames from means and pvals. Being a newbie, I haven't figured out how to sync fork and can't make a pull request. Sorry :(
Please see below
```
ct1 = grep(paste0("^",cell_type1,"$"), substr(colnames(means_mat),start = 1, stop =  nchar(cell_type1)), value = TRUE)
	ct2 = grep(paste0("^",cell_type2,"$"), substr(colnames(means_mat),start = 1, stop =  nchar(cell_type2)), value = TRUE)
    checklabels2 <- any(colnames(means) %in% c(paste0(ct1,"|",ct2), paste0(ct2,"|",ct1)))
```

**Comment by zktuong** [comment]
No worries. You can delete the fork and re-fork. The current version of the package is ```1.0.18```

I've reverted the grep back to original as it is a bit simpler.

You can specify celltype in the current function with standard regex like the following to get more specific columns.
```R
cell_type1 = "^Mphages_I$"
cell_type1 = "^Mphages_[123]$
```

K

**Comment by zktuong** [comment]
> Hi,
> 
> thanks for using this.
> 
> I've updated the code for plot_cpdb slightly. Can you reinstall and try now and see if it now handles more than 2 levels?
> 
> Cheers
> K

I can also confirm that this now works for more than 2 factors, as long as the cell annotation info for input to cpdb can be found in the seurat object.

For example, if the meta.data slot in the seurat object contains a column with:
```R
colnames(seu@meta.data)[9]
[1] "patients"
levels(seu@meta.data[, 'patient'])
[1] "D11" "D12" "D13" "D14"
```
and that there are 2 cell types of interest:
```R
[1] "Macrophage" "Tcell"
```

the cell_type info provided to cpdb should look like the following:
```
Cell	cell_type
GATGAGGCACCCTATC	D11_Macrophage
ACATGGTAGTATGACA	D11_Macrophage
ACTTGTTAGTACATGA	D11_Macrophage
ATCATGGAGATCCTGT	D11_Tcell
CAAGTTGGTCTAGCCG	D11_Tcell
CGATGTAAGTGCCAGA	D12_Macrophage
GGACGTCGTGGTAACG	D13_Tcell
AACTCAGCAGTCGTGC	D11_Tcell
AACTCTTCACATGGGA	D12_Tcell
ACACTGAAGTGAATTG	D13_Macrophage
ACATGGTAGAACAATC	D14_Tcell
ACATGGTTCTCTTATG	D14_Tcell
ACGATACCAATAACGA	D14_Macrophage
```

then specifying this should work:
```R
split.by = 'patient'
```
K

**Comment by saeedfc** [comment]
Hi,

Thanks. I will try this. Iam closing the issue for now.
Saeed

**Comment by zktuong** [comment]
> No worries. You can delete the fork and re-fork. The current version of the package is `1.0.18`
> 
> I've reverted the grep back to original as it is a bit simpler.
> 
> You can specify celltype in the current function with standard regex like the following to get more specific columns.
> 
> ```r
> cell_type1 = "^Mphages_I$"
> cell_type1 = "^Mphages_[123]$
> ```
> 
> K



> No worries. You can delete the fork and re-fork. The current version of the package is `1.0.18`
> 
> I've reverted the grep back to original as it is a bit simpler.
> 
> You can specify celltype in the current function with standard regex like the following to get more specific columns.
> 
> ```r
> cell_type1 = "^Mphages_I$"
> cell_type1 = "^Mphages_[123]$
> ```
> 
> K

I was wrong. currently using special characters only partially works, like using $ at the end of the term. need to come up with a different way to adjust this.

**Comment by zktuong** [comment]
All fixed up now
