### ISSUE TITLE
plot_cpdb: Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

### ISSUE THREAD

**Issue by jreimertz** [zktuong/ktplots#101]
Hello! I keep getting the following error when trying to run `plot_cpdb()`: 

```
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```
![image](https://github.com/zktuong/ktplots/assets/119626411/96921446-6183-4b72-8a17-4ea378db277b)

This is how I've been calling the function:

```
plot_cpdb(
    scdata=dura,
    cell_type1="immature B",
    cell_type2=".", 
    celltype_key="cell_type",
    means=means3,
    pvals=pvals3,
    degs_analysis = T,
    title="interacting interactions!"
)
```

So far in attempting to resolve this issue I've tried: 
- Using a Seurat object as well as a SingleCellExperiment object
- Renaming `means` and `pvals` in case they're being overwritten
- Changing the celltype_key to different columns within the metadata
- Changing `cell_type1` and `cell_type2` to different cell types as well as "."

Running the function with the results of method 2 instead of method 3 resulted in the following error:
![image](https://github.com/zktuong/ktplots/assets/119626411/0ce9721e-201f-4bc5-80c7-fc0e834906ee)

I haven't been able to reproduce this error with the sample `kidneyimmune` dataset which makes me think the issue might be with my CellPhoneDB results but I'm not sure what could be causing the issue. Thank you in advance!

**Comment by zktuong** [comment]
hi @jreimertz yes this is a known issue at the moment but i haven't been able to find time to work on a good fix. tried it at #97 #99 to address #91 but not working at the moment

My current guess is that the issue is the pvals/relevant interaction file has different dimensions to the means file because the newer versions of cellphonedb trims the output.

The current manual fix is to try and duplicate the means file and pad the missing rows/columns with 1 or 0 (depending on whether it's statistical or deg mode respectively) like the suggested fix at https://github.com/zktuong/ktplotspy/issues/51

Would you be able to help me check if adding the missing row/columns for your data works?

**Comment by jreimertz** [comment]
I can confirm that pvals and means have different dimensions

```
> dim(means3)
[1] 2088  337
> dim(pvals3)
[1] 851 337
```

Unfortunately padding the missing rows in pvals led to a different error
![image](https://github.com/zktuong/ktplots/assets/119626411/b705f48c-5ec8-4adb-91a5-338a27345ae2)

I've included the code I used to pad the rows in pvals
```
mat <- matrix(0, 1237, 337)
colnames(mat) <- colnames(pvals3)
pvals_test <- bind_rows(pvals3, as_tibble(mat) %>%
  mutate(across(everything(), ~ `class<-`(.x, class(pvals3[[cur_column()]])))))
```
```
> dim(means3) == dim(pvals_test)
[1] TRUE TRUE
```

**Comment by zktuong** [comment]
What about slicing means to contain the same interactions?

**Comment by zktuong** [comment]
oh i think your attempt to pad the rows throwing your issues because you didn't account for the first 11 or 15 columns where there's the usual information about the LR.

**Comment by zktuong** [comment]
hi @jreimertz , can you try installing the PR at 
- #104 

```R
devtools::install_github("zktuong/ktplots", ref="fix-uneven-rows-and-columns")
```

and see if that helps?

**Comment by jreimertz** [comment]
Hi @zktuong, I've installed the PR you referenced but attempting to run `plot_cpdb()` led to the following error:
![image](https://github.com/zktuong/ktplots/assets/119626411/70accc5e-2bc6-4779-996b-dc68d3c2c93a)
Which was the error I got originally when trying to run the results from the second method

Slicing means to contain the same number of rows as pvals led to the original error:
![image](https://github.com/zktuong/ktplots/assets/119626411/cce82650-2f1d-40d6-9ca6-49be637a4fc1)

**Comment by zktuong** [comment]
Hmm puzzling. Could you send me your cellphonedb output files so that i can do some more testing? You can send them to z.tuong@uq.edu.au

**Comment by zktuong** [comment]
ok the issue is with `tidyverse` was used to read in the `means` and `relevant_interactions` files.
