### ISSUE TITLE
problems with plot_cpdb using cellphonedb v5 outputs

### ISSUE THREAD

**Issue by Zifeng-L** [zktuong/ktplots#109]
Hello, here are some updates with cellphoneDB v5 outputs.
The "means" and "pvals" file have been changed.
![e34c8dfb3baaaf5b4f9621946c92bb4](https://github.com/zktuong/ktplots/assets/53402047/c0c5d728-3545-4421-89bd-c839e51a389e)
Because the column 'interacting_pair' is missing in the dataset, many functions in util.R cannot find this parameter.
![1714189904489](https://github.com/zktuong/ktplots/assets/53402047/53a20426-a7cb-4980-a3bf-09f8d868a154)
![1714189931778](https://github.com/zktuong/ktplots/assets/53402047/db643cf9-392f-4476-b580-f7cc80499476)

**Comment by zktuong** [comment]
Hi, you are using the wrong input for this. your `means` looks like it's `deconvoluted`.
