### ISSUE TITLE
mislead example in _legacy_README.md

### ISSUE THREAD

**Issue by maozhy3** [zktuong/ktplots#112]
the example in _legacy_README.md seems like we should input a sce data and p value, but actially only pvalue is needed, and celltype is used to determine cells to show.

the following piece is enough to get the plot:
plot_cpdb_heatmap(pval=pvalues,  cellheight = 10, cellwidth = 10,degs_analysis = TRUE)

**Comment by zktuong** [comment]
Hi, yes you are correct. the legacy readme is just there in case i route back to it to work on some of the deprecated functions. So can feel free to ignore it.
