### ISSUE TITLE
Error when including special characters in plot_cpdb3()

### ISSUE THREAD

**Issue by jreimertz** [zktuong/ktplots#114]
Hi,

Thanks for making this great tool! I recently found that if I include cell types with special characters in `plot_cpdb3()` I get the following error:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function 'which': subscript contains invalid names
```

After doing some digging in the source code for `plot_cpdb()` and `plot_cpdb3()`, I believe the issue can be resolved by adding a `special_characters_regex_pattern` argument to `plot_cpdb3()` as well as the subsequent checks to include this functionality as they appear in `plot_cpdb()`

**Comment by zktuong** [comment]
hi @jreimertz

currently `plot_cpdb3` should pass any `plot_cpdb` accepted argument should the ellipsis argument `...` so in theory `special_characters_regex_pattern` can be passed directly from `plot_cpdb3`. Does this help solve your issue?

**Comment by jreimertz** [comment]
Hi @zktuong,

Unfortunately it does not, if I include the `special_characters_regex_pattern` argument I get an `unused argument` error. 

I believe this is due to the error occurring after `plot_cpdb()` is called within `plot_cpdb3()`.
When I follow the traceback from the error to the source code for `plot_cpdb3()` I can see that the error occurs within the `.cellTypeFraction_complex()` function, specifically in the following line:

```
sce_[which(SingleCellExperiment::rowData(sce_)[, "index"] %in% genes), ]
```
For your reference, the full traceback is as follows:
![image](https://github.com/user-attachments/assets/1369e867-1289-497f-8e45-02e05f982907)
![image](https://github.com/user-attachments/assets/9b4e03c3-a15e-45f8-91a8-4fadd5431fa9)

**Comment by zktuong** [comment]
hmm but `.cellTypeFraction_complex` shouldn't care about the celltype labels. I noticed that you didn't specify `genes`/`gene_family` in your `plot_cpdb3` call - could you try and add that and see if it helps?

**Comment by jreimertz** [comment]
specifying `genes`/`gene_family` does get around the issue

**Comment by zktuong** [comment]
ok. can i ask you to send me your cellphonedb results, your seurat/singlecell object, and your scripts/notebooks so i can do some testing on my side?
