### ISSUE TITLE
interaction_annotation to replicate plot_cpdb2 plot in vignette

### ISSUE THREAD

**Issue by JackieMium** [zktuong/ktplots#123]
Hi I am trying to follow the ktplot vignette at https://zktuong.github.io/ktplots/articles/vignette.html to vasualize my CellPhoneDb results. However the `plot_cpdb2` example below (copy & paste code from vignette site):

```
data(cpdb_output2) # legacy reasons
plot_cpdb2(
    scdata = kidneyimmune,
    cell_type1 = "B cell",
    cell_type2 = ".",
    celltype_key = "celltype", # column name where the cell ids are located in the metadata
    means = means2,
    pvals = pvals2,
    deconvoluted = decon2, # new options from here on specific to plot_cpdb2
    desiredInteractions = list(
        c("CD4T cell", "B cell"),
        c("B cell", "CD4T cell")
    ),
    interaction_grouping = interaction_annotation,
    edge_group_colors = c(
        "Activating" = "#e15759",
        "Chemotaxis" = "#59a14f",
        "Inhibitory" = "#4e79a7",
        "Intracellular trafficking" = "#9c755f",
        "DC_development" = "#B07aa1",
        "Unknown" = "#e7e7e7"
    ),
    node_group_colors = c(
        "CD4T cell" = "red",
        "B cell" = "blue"
    ),
)
```
uses `interaction_grouping = interaction_annotation` which is no where to be found after I did `library('ktplots')` and `data(cpdb_output2)`. I am wondering where this data comes from and how to prepare it from my own results.

Thanks!
J

**Comment by zktuong** [comment]
Hi @JackieMium , sorry it wasn't obvious but if you look at the tutorial again, there's a link to a google doc:

![image](https://github.com/user-attachments/assets/94ea3c91-668a-4fab-a8e9-f2c91a407dee)

**Comment by JackieMium** [comment]
> Hi @JackieMium , sorry it wasn't obvious but if you look at the tutorial again, there's a link to a google doc:
> 
> ![image](https://private-user-images.githubusercontent.com/26215587/398285242-94ea3c91-668a-4fab-a8e9-f2c91a407dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDY2ODUsIm5iZiI6MTczNTAwNjM4NSwicGF0aCI6Ii8yNjIxNTU4Ny8zOTgyODUyNDItOTRlYTNjOTEtNjY4YS00ZmFiLWE4ZTktZjJjOTFhNDA3ZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAyMTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZWYyZjU4ZmIwM2IwNzJmYTQ1YzU5OTk1MjM4MWZjYjVlNTdkYzFhNzE3OTkyOTVjN2E1MjU3ZTBlMTY3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VzdMc7bUt5h1NPvJ6hQ4ZPTzpP3ugMASsqegSnNcS70)

I did see that, but I am not sure how to use that sheet in the code. Do I pass it as a `dataframe` without any modification? Do I pass a named `vector`? The example code just used `interaction_annotation` without specify what it is and there is no way to tell what `interaction_annotation` is and what it looks like.

**Comment by zktuong** [comment]
Yes just provide as a dataframe
