### ISSUE TITLE
x-axis order using split.by 

### ISSUE THREAD

**Issue by misterygirl2** [zktuong/ktplots#16]
Hi,
 
I used split.by="Experiment" function to list the order of the x-axis labels like the first image, but the order of the x-axis keeps appearing as in the image below. How can I fix it?

Thanks!

![스크린샷 2021-04-19 오전 12 10 02](https://user-images.githubusercontent.com/70194760/115150498-a5667200-a0a3-11eb-8d46-c21907ae35b7.png)

![스크린샷 2021-04-19 오전 12 11 39](https://user-images.githubusercontent.com/70194760/115150555-d777d400-a0a3-11eb-9b60-cce9c5c499f3.png)

**Comment by zktuong** [comment]
Hi @misterygirl2, thank you for alerting me to this.

I've added a fix to this in #17 which I will merge to master once checks are complete.

The way to interact with this now is to change the factor levels of the `split.by` column in the single-cell data:

```R
library(ktplots)
library(Seurat)
data(kidneyimmune)
data(cpdb_output)

levels(kidneyimmune$Experiment)
#  [1] "PapRCC"  "RCC1"    "RCC2"    "RCC3"    "Teen Tx" "TxK1"    "TxK2"    "TxK3"    "TxK4"    "VHLRCC"  "Wilms1" 
# [12] "Wilms2"  "Wilms3" 

plot_cpdb(cell_type1 = 'B cell', cell_type2 = 'CD4T cell', scdata = kidneyimmune,
	idents = 'celltype', # column name where the cell ids are located in the metadata
	split.by = 'Experiment', # column name where the grouping column is. Optional.
	means = means, pvals = pvals,
	genes = c("XCR1", "CXCL10", "CCL5"))
```
This is the original, and creates the following plot:
![image](https://user-images.githubusercontent.com/26215587/115159537-82c85f00-a08b-11eb-8607-edf3fc5334a2.png)


Now, by adjusting the factor levels in the `split.by` column in the single-cell data:
```R	
kidneyimmune$Experiment <- factor(kidneyimmune$Experiment, levels = c("Wilms2", "TxK1",  "RCC2", "RCC3", "TxK4", "VHLRCC", "Wilms1", "PapRCC", "RCC1",  "Teen Tx", "TxK2", "TxK3",  "Wilms3"))

plot_cpdb(cell_type1 = 'B cell', cell_type2 = 'CD4T cell', scdata = kidneyimmune,
	idents = 'celltype', # column name where the cell ids are located in the metadata
	split.by = 'Experiment', # column name where the grouping column is. Optional.
	means = means, pvals = pvals,
	genes = c("XCR1", "CXCL10", "CCL5"))
```
we get this plot:
![image](https://user-images.githubusercontent.com/26215587/115159539-86f47c80-a08b-11eb-822d-94c6e6ccdce5.png)

I will update this thread again once it's been merged.

**Comment by zktuong** [comment]
Ok it's now been merged. Please re-install and check that ktplots is now version 1.1.10.

Feel free to let me know if there's any other issues.

Thank you,

Kelvin

**Comment by misterygirl2** [comment]
It works well! Thanks!!
