### ISSUE TITLE
order of the columns 

### ISSUE THREAD

**Issue by rachel662** [zktuong/ktplots#18]
Hi there, 
sorry to have another question but I was wondering about how the order of the columns are achieved 
Is there a way to change the order of the columns you get at all? 

Thanks so much again

**Comment by zktuong** [comment]
Hi, i think it should respect the factor level in the single cell object. Need to do more testing to see if it works like that.

**Comment by zktuong** [comment]
Just realised i've already answered this in a previous issue #16

**Comment by zktuong** [comment]
Actually, after testing a bit, the linked solution in #16 only works on the `split.by` option.
To have full control of the x-axis ordering, the easiest way is to change the factor level of the return object.

For instance:
```R
g <- plot_cpdb(cell_type1 = 'CD4T cell', cell_type2 = 'B cell', scdata = kidneyimmune,
	idents = 'celltype', # column name where the cell ids are located in the metadata
	split.by = 'Experiment', # column name where the grouping column is. Optional.
	means = means, pvals = pvals,
	genes = c("XCR1", "CXCL10", "CCL5"))
```
where `g` will return the plot similar to the one in the readme.

By changing the factor level of `g$data$Var2` (i'm just reversing them here), I can change the order of the x-axis:
```R
g$data$Var2 <- factor(g$data$Var2, levels = rev(levels(g$data$Var2)))
g
```
![image](https://user-images.githubusercontent.com/26215587/120616030-c830c800-c450-11eb-9e6c-6b8c48f970a8.png)
