### ISSUE TITLE
How can I use "plot_cpdb2"

### ISSUE THREAD

**Issue by EikoSAIJOU334** [zktuong/ktplots#21]
Hi,
I'm analyzing scRNA-seq data and using cellPhoneDB. Your ktplots is very useful to visualize CPDB results. Fantastic!

I'm trying to trace your readme instruction on my jupyter notebook, and it almost worked.

But, "plot_cpdb2" part is hardly worked. Maybe because I can't import "anndata".
When I put this command,
`ad=import('anndata')`
jupyter returns this message;
`Error in py_module_import(module, convert = convert): ModuleNotFoundError: No module named 'anndata'`

I already installed anndata via another jupyter notebook.

How can I use "plot_cpdb2"?

Thanks a lot,
Eiko

**Comment by EikoSAIJOU334** [comment]
Oh, thank you for your quick reply.
I'll use my Seurat object for this purpose, and post the result in this issue.

BTW, my Seurat object is made by mouse data, (converted to the corresponding human gene),
is it possible to use this Seurat object?

**Comment by zktuong** [comment]
hi @EikoSAIJOU334 please note that there is currently a bug with `plot_cpdb2` and i'm trying to fix it at #24. related thread at #23
