### ISSUE TITLE
GeneDot Plot to plot meta - data variable

### ISSUE THREAD

**Issue by saeedfc** [zktuong/ktplots#25]
Hi,

Have been a fan of this tool set you created for some time. an interesting addition will be to allow a nueric variable from the meta data also to be plotted using genedotplot. Using rbind the selected metadata features can be combined with the gene expr_matrix and then the combined expr_matrix can be sued to plot, right?

**Comment by zktuong** [comment]
Thanks @saeedfc. would you be able to mock up an example/doodle something so i can see what you would like as the feature? I can also work with you as a PR to this.
