### ISSUE TITLE
Issue with "plot_cpdb3"

### ISSUE THREAD

**Issue by byemypast** [zktuong/ktplots#41]
First of all, great thanks to your amazing work, which helps me a lot in CPDB visualization.
All worked well when I use plot_cpdb. However when I try to use plot_cpdb3 on my data, it shows 
"Error in sce_alt[[splitted]]: attempt to select less than one element in get1index"

`
>Traceback:
>1. plot_cpdb3(cell_type1 = "T12", cell_type2 = "T15", scdata = data2, 
 .     idents = "leiden2", means = means, pvals = pvalues, deconvoluted = deconvoluted, 
 .     )
>2. .generateDf(ligand = ligand, sep = sep, receptor = receptor, 
 .     receptor_a = receptor_a, receptor_b = receptor_b, pair = pair, 
 .     converted_pair = converted_pair, producers = producers, receivers = receivers, 
 .     cell_type_means = expr_df, cell_type_fractions = fraction_df, 
 .     sce = sce_subset, sce_alt = sce_list_alt, gsm = gene_symbol_mapping)
>3. .cellTypeExpr_complex(sce_alt[[splitted]][[producers[i]]], ligand[j], 
 .     gsm)
>4. tryCatch(sce_[genes, ], error = function(e) {
 .     if (!is.null(gene_symbol_mapping)) {
 .         sce_[which(SingleCellExperiment::rowData(sce_)[, gene_symbol_mapping] %in% 
 .             genes), ]
 .     }
 .     else {
 .         sce_[which(SingleCellExperiment::rowData(sce_)[, "index"] %in% 
 .             genes), ]
 .     }
 . })
>5. tryCatchList(expr, classes, parentenv, handlers)
>6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
>7. value[[3L]](cond

Here are my code

`
>library(SingleCellExperiment)
data2 = as.SingleCellExperiment(data)
rowData(data2)$gene_symbols <- row.names(data2)

>plot_cpdb3(cell_type1 = 'T12', cell_type2 = 'T15',
    scdata = data2,
    idents = 'leiden2', # column name where the cell ids are located in the metadata
    means = means,
    pvals = pvalues,
    deconvoluted = deconvoluted, # new options from here on specific to plot_cpdb3
    )
`

My data's here and wish it could help
`
>>data2
class: SingleCellExperiment 
dim: 25900 9131 
metadata(0):
assays(2): counts logcounts
rownames(25900): TSPAN6 TNMD ... AC007846.2 AP000646.1
rowData names(1): gene_symbols
colnames(9131): AACACACAGAAGGTGGTAAAGGAGTCT AACACACAGAAGGTGGTATACGCGTAC
  ... TGTGGACACTTGCCGTCATGTACGCCT TGTGGACACTTGGTGACCTGCCAACAT
colData names(11): orig.ident nCount_RNA ... leiden2 ident
reducedDimNames(0):
altExpNames(0):

>>data2$leiden2
'T2''T0''T6''T1''T10''T1''T9''T2''T8''T4''T1''T12''T10''T3''T0''T6''T2''T5''T3''T10''T1'....

>>head(means)
	id_cp_interaction	interacting_pair	partner_a	partner_b	gene_a	gene_b	secreted	receptor_a	receptor_b	annotation_strategy	⋯	T9|T14	T9|T15	T9|T2	T9|T3	T9|T4	T9|T5	T9|T6	T9|T7	T9|T8	T9|T9
<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	⋯	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>
1	CPI-CS0A5B6BD7A	12oxoLeukotrieneB4_byPTGR1_LTB4R	complex:12oxoLeukotrieneB4_byPTGR1	simple:Q15722		LTB4R	True	False	True	curated	⋯	0.075	0	0.066	0.067	0.067	0.067	0.068	0.068	0.067	0.067
2	CPI-CS047D9C0D7	LeukotrieneB4_byLTA4H_LTB4R	complex:LeukotrieneB4_byLTA4H	simple:Q15722		LTB4R	True	False	True	curated	⋯	0.317	0	0.308	0.310	0.309	0.310	0.311	0.310	0.309	0.309
3	CPI-CS04A56D5BE	12oxoLeukotrieneB4_byPTGR1_LTB4R2	complex:12oxoLeukotrieneB4_byPTGR1	simple:Q9NPC1		LTB4R2	True	False	True	curated	⋯	0.000	0	0.000	0.066	0.000	0.065	0.065	0.066	0.066	0.000
4	CPI-CS0F5B070C5	LeukotrieneB4_byLTA4H_LTB4R2	complex:LeukotrieneB4_byLTA4H	simple:Q9NPC1		LTB4R2	True	False	True	curated	⋯	0.000	0	0.000	0.309	0.000	0.307	0.308	0.309	0.309	0.000
5	CPI-CS01FC3CF4D	LeukotrieneC4_byLTC4S_CYSLTR2	complex:LeukotrieneC4_byLTC4S	simple:Q9NS75		CYSLTR2	True	False	True	curated	⋯	0.000	0	0.000	0.000	0.000	0.000	0.000	0.000	0.000	0.000
6	CPI-CS0A0F970F5	LeukotrieneD4_byGGT1_CYSLTR2	complex:LeukotrieneD4_byGGT1	simple:Q9NS75		CYSLTR2	True	False	True	curated	⋯	0.000	0	0.000	0.000	0.000	0.000	0.000	0.000	0.000	0.000

>>head(pvalues)
	id_cp_interaction	interacting_pair	partner_a	partner_b	gene_a	gene_b	secreted	receptor_a	receptor_b	annotation_strategy	⋯	T9|T14	T9|T15	T9|T2	T9|T3	T9|T4	T9|T5	T9|T6	T9|T7	T9|T8	T9|T9
<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	⋯	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>
1	CPI-CS0A5B6BD7A	12oxoLeukotrieneB4_byPTGR1_LTB4R	complex:12oxoLeukotrieneB4_byPTGR1	simple:Q15722		LTB4R	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1
2	CPI-CS047D9C0D7	LeukotrieneB4_byLTA4H_LTB4R	complex:LeukotrieneB4_byLTA4H	simple:Q15722		LTB4R	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1
3	CPI-CS04A56D5BE	12oxoLeukotrieneB4_byPTGR1_LTB4R2	complex:12oxoLeukotrieneB4_byPTGR1	simple:Q9NPC1		LTB4R2	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1
4	CPI-CS0F5B070C5	LeukotrieneB4_byLTA4H_LTB4R2	complex:LeukotrieneB4_byLTA4H	simple:Q9NPC1		LTB4R2	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1
5	CPI-CS01FC3CF4D	LeukotrieneC4_byLTC4S_CYSLTR2	complex:LeukotrieneC4_byLTC4S	simple:Q9NS75		CYSLTR2	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1
6	CPI-CS0A0F970F5	LeukotrieneD4_byGGT1_CYSLTR2	complex:LeukotrieneD4_byGGT1	simple:Q9NS75		CYSLTR2	True	False	True	curated	⋯	1	1	1	1	1	1	1	1	1	1

>>head(deconvoluted)
	gene_name	uniprot	is_complex	protein_name	complex_name	id_cp_interaction	T0	T1	T10	T11	⋯	T14	T15	T2	T3	T4	T5	T6	T7	T8	T9
<chr>	<chr>	<chr>	<chr>	<chr>	<chr>	<dbl>	<dbl>	<dbl>	<dbl>	⋯	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>	<dbl>
1	PTGR1	Q14914	True	PTGR1_HUMAN	12oxoLeukotrieneB4_byPTGR1	CPI-CS0A5B6BD7A	0.190	0.244	0.248	0.263	⋯	0.02	0.313	0.359	0.232	0.338	0.295	0.139	0.284	0.220	0.129
2	PTGR1	Q14914	True	PTGR1_HUMAN	12oxoLeukotrieneB4_byPTGR1	CPI-CS04A56D5BE	0.190	0.244	0.248	0.263	⋯	0.02	0.313	0.359	0.232	0.338	0.295	0.139	0.284	0.220	0.129
3	DAGLA	Q9Y4D2	True	DGLA_HUMAN	2arachidonoylglycerol_byDAGLA	CPI-CS03629A52A	0.012	0.012	0.011	0.001	⋯	0.00	0.000	0.007	0.005	0.013	0.015	0.015	0.006	0.015	0.006
4	DAGLA	Q9Y4D2	True	DGLA_HUMAN	2arachidonoylglycerol_byDAGLA	CPI-CS045C37E64	0.012	0.012	0.011	0.001	⋯	0.00	0.000	0.007	0.005	0.013	0.015	0.015	0.006	0.015	0.006
5	DAGLB	Q8NCG7	True	DGLB_HUMAN	2arachidonoylglycerol_byDAGLB	CPI-CS007D418BE	0.039	0.040	0.038	0.050	⋯	0.00	0.168	0.040	0.042	0.037	0.043	0.041	0.040	0.040	0.017
6	DAGLB	Q8NCG7	True	DGLB_HUMAN	2arachidonoylglycerol_byDAGLB	CPI-CS01F7D06F1	0.039	0.040	0.038	0.050	⋯	0.00	0.168	0.040	0.042	0.037	0.043	0.041	0.040	0.040	0.017
`

Thanks a lot

**Comment by zktuong** [comment]
Hi @byemypast, thanks a lot for using this and for reporting this bug!

I think i've found a fix for this. can you reinstall with:
```R
devtools::install_github('zktuong/ktplots', ref = 'fix-complex')
```

and let me know if your plot works now?

**Comment by byemypast** [comment]
Hi zktuong, thanks for your rapidly bug-fixing
I am trying with fix-complex version and it works well with plot_cpdb3,
However when I was trying plot_cpdb4, it shows 

```
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 't': 'data' must be of a vector type, was 'NULL'
Traceback:

1. plot_cpdb4(interaction = c("CSF1R-CSF"), cell_type1 = "T", cell_type2 = "T", 
 .     scdata = data2, idents = "leiden2", means = means, pvals = pvalues, 
 .     deconvoluted = deconvoluted, )
2. data.frame(t(matrix(unlist(tm0), 2, length(unlist(tm0))/2)))
3. t(matrix(unlist(tm0), 2, length(unlist(tm0))/2))
4. matrix(unlist(tm0), 2, length(unlist(tm0))/2)
5. .handleSimpleError(function (cond) 
 . .Internal(C_tryCatchHelper(addr, 1L, cond)), "'data' must be of a vector type, was 'NULL'", 
 .     base::quote(matrix(unlist(tm0), 2, length(unlist(tm0))/2)))
6. h(simpleError(msg, call))
```

my code here,
```
plot_cpdb4(
        interaction = c('CSF1R-CSF'),
        cell_type1 = 'T2', cell_type2 = 'T4',
        scdata = data2,
        idents = 'leiden2',
        means = means,
        pvals = pvalues,
        deconvoluted = deconvoluted,
        )
```

**Comment by zktuong** [comment]
hi @byemypast, i think this is because `plot_cpdb4`'s interaction option has to be exact, so it should be `CSF1R-CSF1` rather than `CSF1R-CSF`.

Because `plot_cpdb4` relies on `plot_cpdb` internally, if the result data table from `plot_cpdb` returns as empty, this same error message will appear.

you can do the following to check:
```R
interaction_result <- plot_cpdb(..., genes = c('CSF1R', 'CSF'), return_table = TRUE)
interaction_result <- interaction_result[interaction_result$Var1 %in% c('CSF1R', 'CSF'), ]
```
