### ISSUE TITLE
Custom input for plot_cpdb2

### ISSUE THREAD

**Issue by showteeth** [zktuong/ktplots#50]
Thank you for providing such a powerful tool!    
I want to create a figure similar to [plot_cpdb2.png](https://github.com/zktuong/ktplots/blob/master/exampleImages/plot_cpdb2.png), and I have filtered CellPhoneDB results with my own demand, so I wonder **if I can pass my filtered data frame to `plot_cpdb2` instead of the whole means and pvalues files**?

My data frames  look like this (**I known the ligand and receptor direction**)：
```R
# P values data frame used
head(celldb.pvalue.used)
     interacting_pair     CellType Pvalue
1         ligand_receptor C2|C1      0
...

# means data frame used
head(celldb.means.used)
     interacting_pair     CellType Means
1         ligand_receptor C2|C1     0.646
```

And do I have to input the `scdata`? What will `plot_cpdb2` do with this file? I analyze the data with `Seurat`.

The last question is about figure legend:
*  `-log10(sig)` is `-log10(Pvalue)` ?
* What does `interaction_score` mean? 
* What does `fraction` mean? 

Thanks.
Yabing

**Comment by zktuong** [comment]
hi @showteeth, thanks for the interest in this package. 

there's a number of moving parts in order for `plot_cpdb2` to work and it currently would not work for the data frame you've generated like that as it expects the output format from `cellphonedb`, which is first 11 columns of means and pvalues to contain the essential first 11 columns (decon table need to have 6 columns (`gene_name`, `uniprot`, `is_complex`, `protein_name`, `complex_name`,  `id_cp_interaction`)) followed by the celltype-celltype interaction entries. the single-cell data is also used to compute the fraction of cell expressing a given gene (indicated by size of the nodes, and the `fraction` legend). The `-log10(sig)` and `interaction_score` are as per the cellphonedb output values found in `pvalues.txt` and `means.txt`. So unlike the other `plot_cpdb` functions, `plot_cpdb2` actually requires the gene expression data from the single-cell data. hopefully this address your questions?

**Comment by showteeth** [comment]
Yes, thanks for your kind help!
