### ISSUE TITLE
standard_scale not working

### ISSUE THREAD

**Issue by diyang1354** [zktuong/ktplots#51]
According to the doc, if set standard_scale to True, it should range from 0 to 1. However, nothing changed

**Comment by zktuong** [comment]
Can you show me the code you used? seems to be working on my end.

**Comment by diyang1354** [comment]
ad_7207 <- readH5AD('../7207hsc/scHSCIntegrated_7207.h5ad')
pvals <- read.delim("../LR_cpdb/7207_0.1/pvalues.txt", check.names = FALSE)
means <- read.delim("../LR_cpdb/7207_0.1/means.txt", check.names = FALSE)
plot_cpdb(cell_type1 = 'Fibroblast|Mo/Mac|Endothelial|Pericyte', cell_type2 = 'HSC', scdata = ad_7207,keep_significant_only = T,
               idents = 'new_clusters_final',
               means = means, pvals = pvals,scale = F,standard_scale = T,max_size = 5,highlight_size = 0.5)
![image](https://user-images.githubusercontent.com/51859749/202442098-b3f80aac-036e-4551-ba29-d668c0448d4b.png)
If set to False:
![image](https://user-images.githubusercontent.com/51859749/202442190-afcf5ec0-f4b3-47b7-96a4-7d096153c3d3.png)

**Comment by diyang1354** [comment]
My apology, it works now if set scale to True first.
Best
