### ISSUE TITLE
using own data for viz

### ISSUE THREAD

**Issue by Pedramto89** [zktuong/ktplots#57]
I have four files (means, sig_means,deconvoluted & pvalues) coming from CPDB and I want to do the visualization. However, how should I use my own data for visualization while the tutorial is based on kidneyimmune. I am a bit confused.

**Comment by zktuong** [comment]
hi, all you do is swap out the arguments:

```R
plot_cpdb(cell_type1 = 'yourcelltype1', cell_type2 = 'yourcelltype2', scdata = yoursinglecelldataset,
	idents = 'yourcelltypecolumn', # column name where the cell ids are located in the metadata
	means = means, pvals = pvals,
	genes = c("XCR1", "CXCL10", "CCL5"))
```

**Comment by Pedramto89** [comment]
Thank you @zktuong 

This is my code: `plot_cpdb(means = "means.txt", scdata = "obj.h5ad", pvals = "pvaleus.txt",small_axis(fontsize = 3) + small_grid() + small_guide() + small_legend(fontsize = 2))
`



This is the error:
`Error in means_mat$interacting_pair : 
  $ operator is invalid for atomic vectors`

**Comment by zktuong** [comment]
Ok i see that you are using a `h5ad` object. You will first need to convert it into `SingleCellExperiment` object, perhaps using tools like:

https://github.com/theislab/anndata2ri
https://github.com/cellgeni/sceasy

or manually like so:

```R
library(SingleCellExperiment)
library(reticulate)
ad=import('anndata')

adata = ad$read_h5ad('rna.h5ad')
counts <- Matrix::t(adata$X)
row.names(counts) <- row.names(adata$var)
colnames(counts) <- row.names(adata$obs)
sce <- SingleCellExperiment(list(counts = counts), colData = adata$obs, rowData = adata$var)
```

Secondly, you will need to provide the `means` and `pvalues` as dataframe objects first like in the tutorial, rather than just filenames.:

```R
means <- read.delim('means.txt', check.names = FALSE)
pvalues <- read.delim('pvalues.txt', check.names = FALSE)
```

**Comment by Pedramto89** [comment]
Thank you @zktuong  for your prompt response. So, I could save my data in an RDS file. Now, how should I introduce my data to the package?
tip: I could not convert the h5ad for some technical reasons.

**Comment by zktuong** [comment]
Just read in your object with readRDS?

**Comment by Pedramto89** [comment]
how? does ktplot has a command to read RDS?

**Comment by zktuong** [comment]
https://rdrr.io/r/base/readRDS.html

readRDS is a base R function

**Comment by Pedramto89** [comment]
Yes you are right @zktuong I just confused first.

This is the code I use:
`plot_cpdb(cell_type1 = "Acinar_cells",cell_type2 = "CAF",
          scdata = adata, idents = "active.ident",
          means = means, pvals = pvals,small_axis(fontsize = 3) + small_grid() + small_guide() + small_legend(fontsize = 2))`

And this is the error I get:
`Error in plot_cpdb(cell_type1 = "Acinar_cells", cell_type2 = "CAF", scdata = adata,  : 
  Cannot find cell types.
The error is mismatch between cell_type1 and the single cell metadata (or idents provided).`

**Comment by zktuong** [comment]
You need to ensure that there is a column called "active.ident" in your object's metadata or colData. You should play around with the toy examples in the tutorial to see how the objects are set up.

also take a look at this issue: https://github.com/zktuong/ktplots/issues/48
