### ISSUE TITLE
Error in h(simpleError(msg, call))

### ISSUE THREAD

**Issue by AShahzad9** [zktuong/ktplots#58]
Hi, 

I have been trying to use the plot_cpdb2 function to create the chord plots but I keep getting this error: 

**> p <- plot_cpdb2(cell_type1 = 'fibroblast', cell_type2 = 'monocytes',
+                 scdata = merged_obj.sce,
+                 idents = 'label', # column name where the cell ids are located in the metadata
+                 means = out_mean,
+                 pvals = out_pvalues,
+                 deconvoluted = out_deconvoluted, # new options from here on specific to plot_cpdb2
+                 desiredInteractions = list(
+                   c('monocytes', 'fibroblast'),
+                   c('fibroblast', 'monocytes')),
+                 interaction_grouping = interaction_annotation,
+                 edge_group_colors = c(
+                   "Activating" = "#e15759"
+                 ),
+                 node_group_colors = c(
+                   "monocytes" = "red",
+                   "fibroblast" = "blue"),
+                 keep_significant_only = TRUE,
+                 standard_scale = TRUE,
+                 remove_self = TRUE
+ )
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function 'which': subscript contains invalid names]**

Can you help me understand this better and help me fix it? 

Thanks,
A

**Comment by zktuong** [comment]
Hi, can you post the full error log for me? just want to see which line number this error is appearing on.

Are there any weird characters in your `label` column? like `+`, `/` etc.

**Comment by AShahzad9** [comment]
Hi ,

"Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function 'which': subscript contains invalid names"

Is that what you were after- have also attached a screenshot. 

Does Cpdb2 not work with seurat files ?

![Screenshot (6)](https://user-images.githubusercontent.com/122884839/213198426-784e47b7-820f-4be2-a471-e0f7be9ced0c.png)

There are only underscores in the column, I think

**Comment by zktuong** [comment]
Yea it only works with SingleCellExperiment object. Just convert with Seurat’s as.SingleCellExperiment

I’m not sure what else could be triggering this

**Comment by maximelepetit** [comment]
Hi @zktuong , I have the same issue using SingleCellExperiment object. 

Here the code : 
```
 plot_cpdb3(cell_type1 = 'TumorCells', cell_type2 = 'StemCells',
    scdata = scdata_sce,
    idents = 'new.labels', # column name where the cell ids are located in the metadata
    means = mean_log_cpdb,
    pvals = pvalue_cpdb,
    deconvoluted = decon_cpdb # new options from here on specific to plot_cpdb3
    )

```
Here R error's  traceback : 
```

Error in get(as.character(FUN), mode = "function", envir = envir) : 
objet 'as.SimpleList' de mode 'function' introuvable
24.
stopifnot(length(class2) == 1L)
23.
is(maybeMethod, "MethodDefinition")
22.
callNextMethod()
21.
methods:::loadMethod(new("MethodWithNext", .Data = function (from, 
to) 
{
ans <- try(callNextMethod(), silent = TRUE) ...
20.
methods:::loadMethod(new("MethodWithNext", .Data = function (from, 
to) 
{
ans <- try(callNextMethod(), silent = TRUE) ...
19.
coerce2(ans, X)
18.
.make_endoapply_ans(ans, X)
17.
endoapply(assays, extract_assay_subset)
16.
.class1(object)
15.
as(endoapply(assays, extract_assay_subset), class(x))
14.
.extract_Assays_subset(x, i, j)
13.
x@assays[ii, ]
12.
x@assays[ii, ]
11.
.nextMethod(x = x, i = i, j = )
10.
callNextMethod()
9.
sce_[genes, ]
8.
sce_[genes, ]
7.
doTryCatch(return(expr), name, parentenv, handler)
6.
tryCatchOne(expr, names, parentenv, handlers[[1L]])
5.
tryCatchList(expr, classes, parentenv, handlers)
4.
tryCatch(sce_[genes, ], error = function(e) {
if (!is.null(gene_symbol_mapping)) {
sce_[which(SingleCellExperiment::rowData(sce_)[, gene_symbol_mapping] %in% 
genes), ] ...
3.
.cellTypeFraction_complex(sce_altx[[producers[i]]], ligand[j], 
gsm)
2.
.generateDf(ligand = ligand, sep = sep, receptor = receptor, 
receptor_a = receptor_a, receptor_b = receptor_b, pair = pair, 
converted_pair = converted_pair, producers = producers, receivers = receivers, 
cell_type_means = expr_df, cell_type_fractions = fraction_df, ...
1.
plot_cpdb3(cell_type1 = "TumorCells", cell_type2 = "StemCells", 
scdata = scdata_sce, idents = "new.labels", means = mean_log_cpdb, 
pvals = pvalue_cpdb, deconvoluted = decon_cpdb)
```
The problem seems to occur when using Large SingleCellExperiment.
