### ISSUE TITLE
Bug Report: plot_cpdb3() "grid_color" parameter

### ISSUE THREAD

**Issue by Tu-feng** [zktuong/ktplots#60]
Hello again, I'm using plot_cpdb3() to plot my cellphoneDB data. 
And I give a named vector for the grid_color parameter(Make sure cell colors are consistent across plots). I found some of my plots are lost without an Error report. Seems the code stoped here because some of my cells have 0 interaction and I still give the cell-color vector for those cells. 
I  tried to delete this if statement and got my lost plots. I think grid.col parameter in chordDiagram() is okay with overqualified named vector.
I'm new to R, and I'm afraid changing this will affect other functions, so maybe you can check it.
THANKS
```R
if (!is.null(grid_cols)) {
--> if (length(grid_cols) != length(unique(tmp_dfx$receiver_swap))) {
        stop(paste0("Please provide ", length(unique(tmp_dfx$receiver_swap)),
                    " to grid_colors."))
    } else {
        grid_color <- grid_cols
    }
} else {
    grid_color <- .scPalette(length(unique(tmp_dfx$receiver_swap)))
}
```

**Comment by zktuong** [comment]
hi @Tu-feng sorry for the slow reply. So are you saying that that line is optional? Can you give me a few more examples?
