### ISSUE TITLE
Adjust spacing of chords in plot_cpdb3

### ISSUE THREAD

**Issue by nhgopee** [zktuong/ktplots#62]
Hi. Thanks for this package which produces really nice plots from CPDB output. I am having issue with the output generated from the plot_cpdb3 and wonder if you have any advice please. If I plot using the kidney data from the example, I get the same plot where the chords are nicely spaced across the circumference/arcs. However, when using my own data the chords are no longer spaced out and occupies the entire edge. I can see there is an option to adjust spacing in the python implementation but I cannot figure out how to do this in the R one. Thanks for any advice.

<img width="499" alt="Screenshot 2023-02-24 at 09 49 14" src="https://user-images.githubusercontent.com/88429288/221148002-82e319b4-2721-4ba5-9c93-cdec3a6037c1.png">

**Comment by zktuong** [comment]
Hi, hmm i'm not sure. i had a look at the circlize tutorial https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html but can't see to find an option to make gaps appears. would plot_cpdb4 serve your purpose?

**Comment by zktuong** [comment]
the only gap options i can see apply to the tracks/arcs, and not the actual links

**Comment by nhgopee** [comment]
Hi, thank you for getting back so quickly. Unfortunately plot_cpdb4  does not seem to work for me - runs for hours with no errors and no outputs. I added genes to plot_cpdb3 to specify my interactions of interest. One potential option I could see form the circlize tutorial is defining the link border width (link.lwd) and link border color (link.border) to widen the gap and setting the color to white maybe, but cannot get it to work so far outside of the defined plot_cpdb3 function. Sorry - pretty new to this! I'll stick with the python version if no easy fix.

**Comment by zktuong** [comment]
I tried the options you mentioned using circlize’s dummy file but it just looks the same to me. Did you manage to get those options to work on circlize’s chordDiagram example?
