### ISSUE TITLE
utils::download.file error

### ISSUE THREAD

**Issue by sheenaseven** [zktuong/ktplots#63]
When I installed this package, I encountered the following problems. Is there any other installation method? I tried to install using another computer and the same error occurred.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/37868618/222378914-916151e7-712d-4ee9-925a-7f83778d1f5b.png">

**Comment by zktuong** [comment]
hi, you can download the latest release from https://github.com/zktuong/ktplots/releases

and then do `install.packages('file.tar.gz', repos = NULL, type="source")`
