### ISSUE TITLE
plot_cpdb_heatmap doesn't support symmetric

### ISSUE THREAD

**Issue by johan-gson** [zktuong/ktplots#69]
Hi and thanks for a nice R package! I see that plot_cpdb_heatmap doesn't support symmetric plots, while the python package does. It would be valuable and appreciated if you could add that, I would be most thankful!

**Comment by zktuong** [comment]
Thanks @johan-gson. I'm a bit busy at the moment so don't have much time to work on this. Will keep this in mind when i find some time.

**Comment by johan-gson** [comment]
Sounds good, thanks for the nice R package!

Best,

Johan

**Comment by zktuong** [comment]
actually it's a lot less work than i thought. testing now at #70 . hopefully merge soon.

**Comment by johan-gson** [comment]
Very nice, many thanks!

Best,

Johan

**Comment by johan-gson** [comment]
Very nice, thank you!

Den lör 1 apr. 2023 00:26Zewen Kelvin Tuong ***@***.***>
skrev:

**Comment by johan-gson** [comment]
@zktuong Hi, I'm having a problem with this, the python and R versions don't produce the same plot. Any idea why this may be?

![PD1_all_heatmap_sym](https://user-images.githubusercontent.com/32481323/229297618-7ebd035a-20b4-4c71-bf0f-fdc3e0aecc86.png)
![Heatmap_sym_All_R](https://user-images.githubusercontent.com/32481323/229297619-d4824e49-48d3-46bf-b94b-ab7dce559faa.png)

**Comment by zktuong** [comment]
Hi, yes sorry. There was a bug on the python version. The one in R is correct. I’ve updated the python version yesterday as well.

**Comment by johan-gson** [comment]
Very nice, thanks, good to know!

Best,

Johan
