### ISSUE TITLE
Changing legend scale and order of labels

### ISSUE THREAD

**Issue by stalware** [zktuong/ktplots#71]
Hello, 
We have 2 datasets we have analyzed at different timepoints and want to compare the interactions using cellphonedb. I am interested in plotting these results as heatmap and was wondering if it is possible to change the scale for legends so that I have them compared to similar scale.
Also, if there is a way to order the rows in specific order?

**Comment by zktuong** [comment]
Hi @stalware, for the first question, have you tried `combine_cpdb` first (if you scroll down a bit on the readme).

For the second Q, you can look at this issue for guidance on how to move the columns: 

https://github.com/zktuong/ktplots/issues/18

For rows, you can try ordering `g$data$Var1`
