### ISSUE TITLE
Interaction plots not working with deg_analysis = TRUE

### ISSUE THREAD

**Issue by Prathyusha-konda** [zktuong/ktplots#76]
Hi, thanks for this repository, very useful with cellphonedb data. I was able to use most functions with my cellphonedb outputs when deg_analysis = FALSE. But when I use data with deg_analysis, I have a couple of problems

1. pvalues after combine_cpd don't have all columns from individual pvalue files, so I can't plot all celltypes on which cellphonedb analysis was performed --- is this expected to happen? I can see the interactions between those celltypes when I look at individual files but they are absent in the combined file.
2. For celltypes which are present in the combined file, interaction plots are not working -- For 1 celltype : 1 celltype interaction plot, it took more than 4 hours and still didn't generate any plot. The same works if I do deg_analysis=FALSE.

Please let me know if I can fix this somehow. Thank you.

**Comment by zktuong** [comment]
Hi @Prathyusha-konda, thank you for the interested in this package.

Can i ask you for more information:
1) what were your full steps to generate the actual cellphonedb runs?
2) how many celltypes do you have in your objects?
3) for your qns 2, which function are you using exactly?
4) Regarding the first question, i'm not sure how that can happen as i'm using `dplyr::full_join`, which should reach a dataframe like this: 
![image](https://github.com/zktuong/ktplots/assets/26215587/a40e07e0-73b8-4d75-afea-d86c32c21e0f)
so can you clarify what you mean when you say you saw the interactions between celltypes at individual files?
