### ISSUE TITLE
could not find function "scale_linewidth" in scale_linewidth(range = c(0, max_highlight_size))

### ISSUE THREAD

**Issue by honghh2018** [zktuong/ktplots#87]
Hi developer,
    It very weird for package ktplots,  
    when i loading the latest package :  the package version was Version: 2.0.0
       library(argparse)
       library(ggplot2)
       library(ktplots)   
       library(Seurat)
and the invoke the function 
p1 <- plot_cpdb(
  scdata=sce,
  cell_type1=args$celltype1,
  cell_type2=args$celltype2,  # this means all cell-types
  celltype_key="ident",
  means=means,
  pvals=pvals,
  title="interacting interactions!",
  gene_family = c('chemokines', 'Th1', 'Th2', 'Th17', 'Treg', 'costimulatory', 'coinhibitory')
)
it show me error lying below:
Calls: plot_cpdb
Execution halted
Error in scale_linewidth(range = c(0, max_highlight_size)) : 
  could not find function "scale_linewidth"
Calls: plot_cpdb
Execution halted

how to fix this issue ?
Best, 
hanhuihong

**Comment by zktuong** [comment]
hi @honghh2018 , your `ggplot2` might be too old? try reinstalling that first

**Comment by honghh2018** [comment]
Thanks the urgent reply, i re-install gglot2 and try it again.
Best,

**Comment by honghh2018** [comment]
I install the ggplot2 version 3.4.4, it work for me
Best,
hanhuihong
