### ISSUE TITLE
problem in plot_cpdb

### ISSUE THREAD

**Issue by GGboy-Zzz** [zktuong/ktplots#88]
Hi, I met a problem with the function "plot_cpdb", Its parameter "cell_type1" or "cell_type2" accepts regex pattern. Can I avoid this regex pattern to specify a unique cell_type?

**Comment by zktuong** [comment]
you can be specific with your regex e.g. `^Tcell$`- this would then force it to look for only `Tcell`. as long as you name your celltypes uniquely. if not, i would suggest for you to insert a unique pattern into your celltype annotations and rerun cellphonedb.
